#order-service:
#server:
 # port: 8082
 # message: "Order Service from Config Server"

#product-service:
#server:
 # port: 8081
#  message: "Product Service from Config Server"

#api-gateway:
#server:
 #  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
      gateway:
        routes:
          - id: order-service
            uri: lb://order-service
            predicates:
              - Path=/orders/**
          - id: product-service
            uri: lb://product-service
            predicates:
              - Path=/products/**
      discovery: 
        locator:
          enabled: true
          lowerCaseServiceId: true        
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
